### ISSUE TITLE
Add ImplementationName and Version to MANIFEST.MF

### ISSUE THREAD

**Issue by ST-DDT** [javafx-maven-plugin/javafx-maven-plugin#220]
Based on : [Stackoverflow: maven javafx plugin: generate MANIFEST](http://stackoverflow.com/questions/36224829/maven-javafx-plugin-generate-manifest)

It would be cool if you could add the following options to the `javafx-maven-plugin` config.

````xml
<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
````
similar to the `maven-jar-plugin` config

this would be the short equivalent of the following:

````xml
<manifestAttributes>
	<Specification-Title>${project.name}</Specification-Title>
	<Specification-Version>${project.version}</Specification-Version>
	<Specification-Vendor>${project.organization.name}</Specification-Vendor>
	<Implementation-Title>${project.name}</Implementation-Title>
	<Implementation-Version>${project.version}</Implementation-Version>
	<Implementation-Vendor-Id>${project.groupId}</Implementation-Vendor-Id>
	<Implementation-Vendor>${project.organization.name}</Implementation-Vendor>
</manifestAttributes>
````

This will result in the following `MANIFEST.MF` file:

````yml
Manifest-Version: 1.0
Implementation-Title: MyApplication
Implementation-Version: 1.3.0-SNAPSHOT
Specification-Vendor: Orga
Implementation-Vendor-Id: de.st-ddt.demo
Specification-Title: MyApplication
Class-Path: [....jars....]
Implementation-Vendor: Orga
Main-Class: de.st-ddt.demo.Launcher
Permissions: sandbox
JavaFX-Version: 8.0
Created-By: JavaFX Packager
Specification-Version: 1.3.0-SNAPSHOT
````

And these values can be accessed via:
````java
MyClass.class.getPackage().getImplementationTitle();
````

Thanks for your work.
